# Configuration for testing Barab√°si-Albert graph from file

experiment_path: .
experiment_output_path: "{PROJECT_ROOT}/output"

# Setup configuration (used by setup commands)
setup:
  map_path: ./resources/test_map.png
  # spatial_image_for_calibration: ./demo_session/memory5-11022023_withrewardafter8min.avi
  # calibration_matrix: ./resources/transform_matrix.npy

graph:
  builder:
    type: file_loader
    config:
      filepath: ./graphs/random_barabasi_albert.graphml
      format: graphml
  mapping_file: ./resources/graph_mapping_barabasi.pkl
  conflict_strategy: node_priority